[workspace]
members = ["apps/enclave", "apps/host", "lib/vault-shared"]
resolver = "3"

[workspace.package]
edition = "2024"

[workspace.dependencies]
tokio-vsock = "0.7"
tokio = { version = "1", features = ["full"] }
tonic = "0.14"
prost = "0.14"
prost-types = "0.14"
tonic-prost = "0.14"
tonic-prost-build = "0.14"
serde = { version = "1.0", features = ["derive"] }
pallas-crypto = "1.1.0"
ed25519-bip32 = "0.4.2"
getrandom = { version = "0.4", features = ["sys_rng"] }
bech32 = "0.12.0"
thiserror = "2.0.18"
pallas-addresses = "1.1.0"
pallas-primitives = "1.1.0"
base64 = "0.22"
serde_cbor = "0.11.2"
aes-gcm = "0.10.3"
vault-shared = { path = "lib/vault-shared" }
