[package]
name = "vault-shared"
version = "0.1.0"
edition.workspace = true

[dependencies]
pallas-crypto = { workspace = true }
ed25519-bip32 = { workspace = true }
bech32 = { workspace = true }
thiserror = { workspace = true }
pallas-addresses = { workspace = true }
base64 = { workspace = true }
serde = { workspace = true }
serde_cbor = { workspace = true }
tokio = { workspace = true }
tokio-vsock = { workspace = true }
